routes/web.php
<?php

Route::get('/', 'DefaultController@welcome')->name('welcome');
Route::post('translate', 'TranslateController@translate');
Route::get('/articles/category/{category_id}' , 'ArticleController@showArticleWhistCategory')->name('article_category');
Route::get('/words', 'WordController@wordsList')->name('words.list');
Route::get('/locale/{locale}' , 'DefaultController@locale')->name('user.set_locale');
Route::get('/login/google', 'AuthorizationController@loginGoogle')->name('google.login');
Route::get('/callback/google', 'AuthorizationController@callbackGoogle');
Route::get('/logout', 'AuthorizationController@logout')->name('logout');
Route::any('/test', 'DefaultController@test')->name('test');
Route::post('/search', 'ArticleController@search')->name('articles.search');

Route::prefix('/')->group(function () {
    Route::resource('articles', 'ArticleController');
});

app/Models/Article.php
<?php


namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'id',
        'title',
        'preview',
        'body',
        'parity',
        'source',
        'url',
        'image',
        'category_id',
        'language',
    ];

    public function category()
    {
        //Статя належить категорії
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Category;
use App\Repositories\ArticleRepository;
use App\Http\Requests\ArticleCreateRequest;
use App\Repositories\CategoryRepository;
use App\Resolvers\TextSeverityResolver;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class ArticleController extends Controller
{
    private $articleRepository;
    private $categoryRepository;
    private $textSeverityResolver;

    public function __construct(TextSeverityResolver $textSeverityResolver)
    {
        $this->articleRepository = app(ArticleRepository::class);
        $this->categoryRepository = app(CategoryRepository::class);
        $this->textSeverityResolver = $textSeverityResolver;
    }

    public function index(Request $request)
    {
        $articlesLanguage = App::getLocale() == 'en' ? 'es' : 'en';
        $articles = Article::where('language', $articlesLanguage);
        $category = $request->get('category');
        $level = $request->get('level');
        $keyword = $request->get('keyword');

        if ($category) {
            $articles = Article::whereHas("category", function ($q) use ($category) {
                $q->where('id', '=', $category);
            });
        }

        if ($level) {
            $articles = $articles->where('parity', $level);
        }

        if ($keyword) {
            $articles = $articles->where('title', 'like', '%'.$keyword.'%');
        }
        $articles = $articles->get();

        return view('articles.index', [
            'articles' => $articles,
            'search' => $request->all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $article = new Article();
        $categoryList = $this->categoryRepository->getForComboBox();

        return view('articles.edit',
            compact('article', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleCreateRequest $request)
    {
        $data = $request->input();
        $data['title'] = strip_tags($data['title']);
        $data['body'] = strip_tags($data['body']);
        $data['preview'] = str_limit($data['body']);

        try {
            $data['parity'] = $this->textSeverityResolver->resolve($data['body']);
        } catch (\Exception $e) {
            return back()->withErrors(['msg' => $e->getMessage()])->withInput();
        }
        $article = (new Article())->create($data);

        if ($article) {
            return redirect()->route('articles.index')
                ->with(['success' => 'Saved successfully']);
        } else {
            return back()->withErrors(['msg' => 'Error saved'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id);

        return view('articles.show', compact('article'));

    }

    public function showArticleWhistCategory($id)
    {
        $articles = Article::query()->select('*')
            ->where('category_id', $id)
            ->paginate(15);

        return view('articles.category.index', compact('articles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

}

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('body')
    @php
        /** @var \App\Models\Article $item */
    @endphp
    <section>
        @include('articles.includes.result_message')
        <form method="POST" action="{{ route('articles.store') }}">
            {{ csrf_field() }}
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('articles.includes.item_edit_add')
                </div>
            </div>
        </form>
    </section>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('body')
        <br>
        @include('includes.search')
        <br><br>
        <div class="articles">
            @foreach($articles as $article)
                @include('articles.includes.get_article')
            @endforeach
{{--            @if($articles->total() > $articles->count())--}}
{{--                <br>--}}
{{--                <div class="row justify-content-center">--}}
{{--                    <div class="col-md-12">--}}
{{--                        <div class="card">--}}
{{--                            {{ $articles->links() }}--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            @endif--}}
        </div>
    <br><br>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('body')
    <div id="article-translate">
        <div>
            <span id="article-translate-original">Original: </span>
            <span id="article-translate-translated">Translated</span>
        </div>
        <div id="article-translate-sentence">Translated sentence</div>
        <div id="article-translate-preloader">{{ __('messages.article_translate_in_progress') }}…</div>
    </div>
    <div class="article ws">
        {{--        <h2>{{ __('messages.article_category') }} : {{ $article->category->category }}</h2>--}}
        {{--        <h2>{{ __('messages.article_level') }} : {{ $article->parity }}</h2><br>--}}
        <div class="article-content">
            <h1>{{ $article->title }}</h1><br>
            {!! $article->body !!}
        </div>
    </div>
@endsection